# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zdavid/Code/pte/hangman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zdavid/Code/pte/hangman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zdavid/Code/pte/hangman/CMakeFiles /home/zdavid/Code/pte/hangman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zdavid/Code/pte/hangman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hangman

# Build rule for target.
hangman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hangman
.PHONY : hangman

# fast build rule for target.
hangman/fast:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/build
.PHONY : hangman/fast

lib/src/categories.o: lib/src/categories.c.o

.PHONY : lib/src/categories.o

# target to build an object file
lib/src/categories.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/categories.c.o
.PHONY : lib/src/categories.c.o

lib/src/categories.i: lib/src/categories.c.i

.PHONY : lib/src/categories.i

# target to preprocess a source file
lib/src/categories.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/categories.c.i
.PHONY : lib/src/categories.c.i

lib/src/categories.s: lib/src/categories.c.s

.PHONY : lib/src/categories.s

# target to generate assembly for a file
lib/src/categories.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/categories.c.s
.PHONY : lib/src/categories.c.s

lib/src/createmenuitem.o: lib/src/createmenuitem.c.o

.PHONY : lib/src/createmenuitem.o

# target to build an object file
lib/src/createmenuitem.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/createmenuitem.c.o
.PHONY : lib/src/createmenuitem.c.o

lib/src/createmenuitem.i: lib/src/createmenuitem.c.i

.PHONY : lib/src/createmenuitem.i

# target to preprocess a source file
lib/src/createmenuitem.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/createmenuitem.c.i
.PHONY : lib/src/createmenuitem.c.i

lib/src/createmenuitem.s: lib/src/createmenuitem.c.s

.PHONY : lib/src/createmenuitem.s

# target to generate assembly for a file
lib/src/createmenuitem.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/createmenuitem.c.s
.PHONY : lib/src/createmenuitem.c.s

lib/src/initializer.o: lib/src/initializer.c.o

.PHONY : lib/src/initializer.o

# target to build an object file
lib/src/initializer.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/initializer.c.o
.PHONY : lib/src/initializer.c.o

lib/src/initializer.i: lib/src/initializer.c.i

.PHONY : lib/src/initializer.i

# target to preprocess a source file
lib/src/initializer.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/initializer.c.i
.PHONY : lib/src/initializer.c.i

lib/src/initializer.s: lib/src/initializer.c.s

.PHONY : lib/src/initializer.s

# target to generate assembly for a file
lib/src/initializer.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/initializer.c.s
.PHONY : lib/src/initializer.c.s

lib/src/main.o: lib/src/main.c.o

.PHONY : lib/src/main.o

# target to build an object file
lib/src/main.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/main.c.o
.PHONY : lib/src/main.c.o

lib/src/main.i: lib/src/main.c.i

.PHONY : lib/src/main.i

# target to preprocess a source file
lib/src/main.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/main.c.i
.PHONY : lib/src/main.c.i

lib/src/main.s: lib/src/main.c.s

.PHONY : lib/src/main.s

# target to generate assembly for a file
lib/src/main.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/main.c.s
.PHONY : lib/src/main.c.s

lib/src/playagame.o: lib/src/playagame.c.o

.PHONY : lib/src/playagame.o

# target to build an object file
lib/src/playagame.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/playagame.c.o
.PHONY : lib/src/playagame.c.o

lib/src/playagame.i: lib/src/playagame.c.i

.PHONY : lib/src/playagame.i

# target to preprocess a source file
lib/src/playagame.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/playagame.c.i
.PHONY : lib/src/playagame.c.i

lib/src/playagame.s: lib/src/playagame.c.s

.PHONY : lib/src/playagame.s

# target to generate assembly for a file
lib/src/playagame.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/playagame.c.s
.PHONY : lib/src/playagame.c.s

lib/src/renderHang.o: lib/src/renderHang.c.o

.PHONY : lib/src/renderHang.o

# target to build an object file
lib/src/renderHang.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/renderHang.c.o
.PHONY : lib/src/renderHang.c.o

lib/src/renderHang.i: lib/src/renderHang.c.i

.PHONY : lib/src/renderHang.i

# target to preprocess a source file
lib/src/renderHang.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/renderHang.c.i
.PHONY : lib/src/renderHang.c.i

lib/src/renderHang.s: lib/src/renderHang.c.s

.PHONY : lib/src/renderHang.s

# target to generate assembly for a file
lib/src/renderHang.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/renderHang.c.s
.PHONY : lib/src/renderHang.c.s

lib/src/renderview.o: lib/src/renderview.c.o

.PHONY : lib/src/renderview.o

# target to build an object file
lib/src/renderview.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/renderview.c.o
.PHONY : lib/src/renderview.c.o

lib/src/renderview.i: lib/src/renderview.c.i

.PHONY : lib/src/renderview.i

# target to preprocess a source file
lib/src/renderview.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/renderview.c.i
.PHONY : lib/src/renderview.c.i

lib/src/renderview.s: lib/src/renderview.c.s

.PHONY : lib/src/renderview.s

# target to generate assembly for a file
lib/src/renderview.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/renderview.c.s
.PHONY : lib/src/renderview.c.s

lib/src/selectcategory.o: lib/src/selectcategory.c.o

.PHONY : lib/src/selectcategory.o

# target to build an object file
lib/src/selectcategory.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/selectcategory.c.o
.PHONY : lib/src/selectcategory.c.o

lib/src/selectcategory.i: lib/src/selectcategory.c.i

.PHONY : lib/src/selectcategory.i

# target to preprocess a source file
lib/src/selectcategory.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/selectcategory.c.i
.PHONY : lib/src/selectcategory.c.i

lib/src/selectcategory.s: lib/src/selectcategory.c.s

.PHONY : lib/src/selectcategory.s

# target to generate assembly for a file
lib/src/selectcategory.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/selectcategory.c.s
.PHONY : lib/src/selectcategory.c.s

lib/src/showcredits.o: lib/src/showcredits.c.o

.PHONY : lib/src/showcredits.o

# target to build an object file
lib/src/showcredits.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/showcredits.c.o
.PHONY : lib/src/showcredits.c.o

lib/src/showcredits.i: lib/src/showcredits.c.i

.PHONY : lib/src/showcredits.i

# target to preprocess a source file
lib/src/showcredits.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/showcredits.c.i
.PHONY : lib/src/showcredits.c.i

lib/src/showcredits.s: lib/src/showcredits.c.s

.PHONY : lib/src/showcredits.s

# target to generate assembly for a file
lib/src/showcredits.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/showcredits.c.s
.PHONY : lib/src/showcredits.c.s

lib/src/showinstructions.o: lib/src/showinstructions.c.o

.PHONY : lib/src/showinstructions.o

# target to build an object file
lib/src/showinstructions.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/showinstructions.c.o
.PHONY : lib/src/showinstructions.c.o

lib/src/showinstructions.i: lib/src/showinstructions.c.i

.PHONY : lib/src/showinstructions.i

# target to preprocess a source file
lib/src/showinstructions.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/showinstructions.c.i
.PHONY : lib/src/showinstructions.c.i

lib/src/showinstructions.s: lib/src/showinstructions.c.s

.PHONY : lib/src/showinstructions.s

# target to generate assembly for a file
lib/src/showinstructions.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/showinstructions.c.s
.PHONY : lib/src/showinstructions.c.s

lib/src/storeanewword.o: lib/src/storeanewword.c.o

.PHONY : lib/src/storeanewword.o

# target to build an object file
lib/src/storeanewword.c.o:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/storeanewword.c.o
.PHONY : lib/src/storeanewword.c.o

lib/src/storeanewword.i: lib/src/storeanewword.c.i

.PHONY : lib/src/storeanewword.i

# target to preprocess a source file
lib/src/storeanewword.c.i:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/storeanewword.c.i
.PHONY : lib/src/storeanewword.c.i

lib/src/storeanewword.s: lib/src/storeanewword.c.s

.PHONY : lib/src/storeanewword.s

# target to generate assembly for a file
lib/src/storeanewword.c.s:
	$(MAKE) -f CMakeFiles/hangman.dir/build.make CMakeFiles/hangman.dir/lib/src/storeanewword.c.s
.PHONY : lib/src/storeanewword.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... hangman"
	@echo "... edit_cache"
	@echo "... lib/src/categories.o"
	@echo "... lib/src/categories.i"
	@echo "... lib/src/categories.s"
	@echo "... lib/src/createmenuitem.o"
	@echo "... lib/src/createmenuitem.i"
	@echo "... lib/src/createmenuitem.s"
	@echo "... lib/src/initializer.o"
	@echo "... lib/src/initializer.i"
	@echo "... lib/src/initializer.s"
	@echo "... lib/src/main.o"
	@echo "... lib/src/main.i"
	@echo "... lib/src/main.s"
	@echo "... lib/src/playagame.o"
	@echo "... lib/src/playagame.i"
	@echo "... lib/src/playagame.s"
	@echo "... lib/src/renderHang.o"
	@echo "... lib/src/renderHang.i"
	@echo "... lib/src/renderHang.s"
	@echo "... lib/src/renderview.o"
	@echo "... lib/src/renderview.i"
	@echo "... lib/src/renderview.s"
	@echo "... lib/src/selectcategory.o"
	@echo "... lib/src/selectcategory.i"
	@echo "... lib/src/selectcategory.s"
	@echo "... lib/src/showcredits.o"
	@echo "... lib/src/showcredits.i"
	@echo "... lib/src/showcredits.s"
	@echo "... lib/src/showinstructions.o"
	@echo "... lib/src/showinstructions.i"
	@echo "... lib/src/showinstructions.s"
	@echo "... lib/src/storeanewword.o"
	@echo "... lib/src/storeanewword.i"
	@echo "... lib/src/storeanewword.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

